-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#1a110f',
  base01 = '#140c0a',
  base02 = '#231917',
  base03 = '#534340',
  base04 = '#d8c2bd',
  base05 = '#f1dfdb',
  base06 = '#392e2c',
  base07 = '#423734',

  base08 = '#ffb4ab',
  base09 = '#dbc48c',
  base0A = '#e7bdb4',
  base0B = '#ffb4a4',
  base0C = '#554519',
  base0D = '#733427',
  base0E = '#5d3f39',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#733427',
  fg = '#1a110f',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#f9e0a6',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#dbc48c',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e7bdb4',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#904b3c',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#140c0a',
  fg = '#ffb4a4',
})
